/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_cstinyxml2_WRAP_H_
#define SWIG_cstinyxml2_WRAP_H_

class SwigDirector_XMLVisitor : public tinyxml2::XMLVisitor, public Swig::Director {

public:
    SwigDirector_XMLVisitor();
    virtual ~SwigDirector_XMLVisitor();
    virtual bool VisitEnter(tinyxml2::XMLDocument const &arg0);
    virtual bool VisitExit(tinyxml2::XMLDocument const &arg0);
    virtual bool VisitEnter(tinyxml2::XMLElement const &arg0,tinyxml2::XMLAttribute const *arg1);
    virtual bool VisitExit(tinyxml2::XMLElement const &arg0);
    virtual bool Visit(tinyxml2::XMLDeclaration const &arg0);
    virtual bool Visit(tinyxml2::XMLText const &arg0);
    virtual bool Visit(tinyxml2::XMLComment const &arg0);
    virtual bool Visit(tinyxml2::XMLUnknown const &arg0);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback6_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackVisitEnter__SWIG_0, SWIG_Callback1_t callbackVisitExit__SWIG_0, SWIG_Callback2_t callbackVisitEnter__SWIG_1, SWIG_Callback3_t callbackVisitExit__SWIG_1, SWIG_Callback4_t callbackVisit__SWIG_0, SWIG_Callback5_t callbackVisit__SWIG_1, SWIG_Callback6_t callbackVisit__SWIG_2, SWIG_Callback7_t callbackVisit__SWIG_3);

private:
    SWIG_Callback0_t swig_callbackVisitEnter__SWIG_0;
    SWIG_Callback1_t swig_callbackVisitExit__SWIG_0;
    SWIG_Callback2_t swig_callbackVisitEnter__SWIG_1;
    SWIG_Callback3_t swig_callbackVisitExit__SWIG_1;
    SWIG_Callback4_t swig_callbackVisit__SWIG_0;
    SWIG_Callback5_t swig_callbackVisit__SWIG_1;
    SWIG_Callback6_t swig_callbackVisit__SWIG_2;
    SWIG_Callback7_t swig_callbackVisit__SWIG_3;
    void swig_init_callbacks();
};


#endif
